name: betanewsfeed
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4304499241989106
title: Testing Page for RT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141420'
    - '#e4e7ec'
    - '#8cafba'
    - '#3a383d'
    - '#73787e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
